CREATE ROLE productappuser WITH LOGIN PASSWORD 'secure_password';

GRANT CONNECT ON DATABASE postgres TO productappuser;
GRANT USAGE ON SCHEMA product TO productappuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA product TO productappuser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA product TO productappuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA product GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO productappuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA product GRANT USAGE, SELECT ON SEQUENCES TO productappuser;